<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="11" ignored="0" total="22" passed="0" failed="11" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-16T18:26:26 IST" name="Suite" finished-at="2025-06-16T18:50:35 IST" duration-ms="1448504">
    <groups>
    </groups>
    <test started-at="2025-06-16T18:26:26 IST" name="NewCompanyTest" finished-at="2025-06-16T18:50:35 IST" duration-ms="1448504">
      <class name="TestCases.NewCompany">
        <test-method is-config="true" signature="extentReportMethod()[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:26:26 IST" name="extentReportMethod" finished-at="2025-06-16T18:26:27 IST" duration-ms="520" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportMethod -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:26:30 IST" name="initialization" finished-at="2025-06-16T18:27:29 IST" duration-ms="59071" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:27:29 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:27:46 IST" duration-ms="16982" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[LTI]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lntinfotech.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[hyderabad]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9999999999]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[2000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [LTI]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [LTI]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:27:46 IST" name="onTestFailure" finished-at="2025-06-16T18:27:47 IST" duration-ms="550" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:27:48 IST" name="initialization" finished-at="2025-06-16T18:29:03 IST" duration-ms="75371" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:29:03 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:29:20 IST" duration-ms="16464" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[LTI]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lntinfotech.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[hyderabad]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9999999999]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[2000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [LTI]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [LTI]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:29:20 IST" name="onTestFailure" finished-at="2025-06-16T18:29:20 IST" duration-ms="372" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:29:20 IST" name="initialization" finished-at="2025-06-16T18:30:02 IST" duration-ms="41535" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:30:02 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:30:17 IST" duration-ms="15588" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[infosys]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[infosys.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[pune]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[8888888888]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[3000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [infosys]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [infosys]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:30:17 IST" name="onTestFailure" finished-at="2025-06-16T18:30:18 IST" duration-ms="408" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:30:19 IST" name="initialization" finished-at="2025-06-16T18:30:43 IST" duration-ms="23959" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:30:43 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:30:58 IST" duration-ms="15684" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[infosys]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[infosys.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[pune]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[8888888888]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[3000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [infosys]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [infosys]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:30:58 IST" name="onTestFailure" finished-at="2025-06-16T18:30:59 IST" duration-ms="423" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:30:59 IST" name="initialization" finished-at="2025-06-16T18:31:49 IST" duration-ms="50267" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:31:49 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:32:06 IST" duration-ms="16522" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[tcs]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tcs.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[kochin]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[7777777777]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [tcs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [tcs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:32:06 IST" name="onTestFailure" finished-at="2025-06-16T18:32:06 IST" duration-ms="329" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:32:07 IST" name="initialization" finished-at="2025-06-16T18:33:15 IST" duration-ms="68399" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:33:15 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:33:31 IST" duration-ms="16151" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tcs]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tcs.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[kochin]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[7777777777]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[4000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [tcs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [tcs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:33:31 IST" name="onTestFailure" finished-at="2025-06-16T18:33:32 IST" duration-ms="441" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:33:32 IST" name="initialization" finished-at="2025-06-16T18:34:29 IST" duration-ms="56937" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:34:29 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:34:45 IST" duration-ms="15794" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[wipro]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wipro.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chennai]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[6666666666]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[5000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [wipro]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [wipro]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:34:45 IST" name="onTestFailure" finished-at="2025-06-16T18:34:45 IST" duration-ms="391" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:34:46 IST" name="initialization" finished-at="2025-06-16T18:34:58 IST" duration-ms="11976" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:34:58 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:35:14 IST" duration-ms="15966" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[wipro]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wipro.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chennai]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[6666666666]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[5000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [wipro]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [wipro]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:35:14 IST" name="onTestFailure" finished-at="2025-06-16T18:35:14 IST" duration-ms="295" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:35:14 IST" name="initialization" finished-at="2025-06-16T18:35:45 IST" duration-ms="30848" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:35:45 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:36:02 IST" duration-ms="17418" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[capgemini]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[capgemini.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[banglore]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[5555555555]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[6000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [capgemini]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [capgemini]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:36:02 IST" name="onTestFailure" finished-at="2025-06-16T18:36:03 IST" duration-ms="364" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:36:03 IST" name="initialization" finished-at="2025-06-16T18:36:50 IST" duration-ms="46265" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:36:50 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:37:07 IST" duration-ms="17013" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[capgemini]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[capgemini.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[banglore]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[5555555555]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[6000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [capgemini]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [capgemini]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:37:07 IST" name="onTestFailure" finished-at="2025-06-16T18:37:07 IST" duration-ms="363" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:37:07 IST" name="initialization" finished-at="2025-06-16T18:37:11 IST" duration-ms="4184" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:37:11 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:38:28 IST" duration-ms="76983" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[flipkart]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[flipkart.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[maharastra]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4444444444]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[7000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element is not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element is not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at pageEvents.LoginPageEvents.verifyIfPageIsLoaded(LoginPageEvents.java:20)
at TestCases.LoginTest.loginTestCase(LoginTest.java:20)
at TestCases.HomePageTest.HomepageTest(HomePageTest.java:23)
at TestCases.NewCompany.addNewCompany(NewCompany.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:38:28 IST" name="onTestFailure" finished-at="2025-06-16T18:38:29 IST" duration-ms="453" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:38:30 IST" name="initialization" finished-at="2025-06-16T18:39:06 IST" duration-ms="36312" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:39:06 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:39:22 IST" duration-ms="16027" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[flipkart]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[flipkart.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[maharastra]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4444444444]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[7000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [flipkart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [flipkart]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:39:22 IST" name="onTestFailure" finished-at="2025-06-16T18:39:22 IST" duration-ms="325" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:39:22 IST" name="initialization" finished-at="2025-06-16T18:39:34 IST" duration-ms="11506" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:39:34 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:39:50 IST" duration-ms="16071" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[amazon]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[amazon.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[kolkata]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[3333333333]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[8000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [amazon]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [amazon]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:39:50 IST" name="onTestFailure" finished-at="2025-06-16T18:39:50 IST" duration-ms="362" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:39:51 IST" name="initialization" finished-at="2025-06-16T18:40:56 IST" duration-ms="65219" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:40:56 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:41:12 IST" duration-ms="15993" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[amazon]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[amazon.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[kolkata]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[3333333333]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[8000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [amazon]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [amazon]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:41:12 IST" name="onTestFailure" finished-at="2025-06-16T18:41:13 IST" duration-ms="340" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:41:13 IST" name="initialization" finished-at="2025-06-16T18:42:17 IST" duration-ms="64437" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:42:17 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:42:30 IST" duration-ms="12976" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[alibaba]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[alibaba.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chaina]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2222222222]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[9000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [alibaba]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [alibaba]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:42:30 IST" name="onTestFailure" finished-at="2025-06-16T18:42:30 IST" duration-ms="296" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:42:31 IST" name="initialization" finished-at="2025-06-16T18:43:05 IST" duration-ms="34548" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:43:05 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:43:18 IST" duration-ms="12924" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[alibaba]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[alibaba.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chaina]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2222222222]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[9000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [alibaba]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [alibaba]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:43:18 IST" name="onTestFailure" finished-at="2025-06-16T18:43:19 IST" duration-ms="212" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:43:19 IST" name="initialization" finished-at="2025-06-16T18:43:42 IST" duration-ms="23609" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:43:42 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:43:55 IST" duration-ms="13213" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[ebay]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ebay.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[usa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1111111111]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[10000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [ebay]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [ebay]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:43:55 IST" name="onTestFailure" finished-at="2025-06-16T18:43:56 IST" duration-ms="229" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:43:56 IST" name="initialization" finished-at="2025-06-16T18:44:19 IST" duration-ms="23134" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:44:19 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:44:32 IST" duration-ms="12829" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ebay]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ebay.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[usa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1111111111]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[10000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [ebay]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [ebay]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:44:32 IST" name="onTestFailure" finished-at="2025-06-16T18:44:32 IST" duration-ms="224" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:44:32 IST" name="initialization" finished-at="2025-06-16T18:45:12 IST" duration-ms="39936" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:45:12 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:45:26 IST" duration-ms="13236" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[google]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[google.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[usa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1234567890]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[11000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [google]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:45:26 IST" name="onTestFailure" finished-at="2025-06-16T18:45:26 IST" duration-ms="236" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:45:26 IST" name="initialization" finished-at="2025-06-16T18:46:40 IST" duration-ms="73551" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:46:40 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:46:53 IST" duration-ms="13601" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[google]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[google.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[usa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1234567890]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[11000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [google]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:46:53 IST" name="onTestFailure" finished-at="2025-06-16T18:46:55 IST" duration-ms="1773" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:46:55 IST" name="initialization" finished-at="2025-06-16T18:48:08 IST" duration-ms="73113" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method retried="true" signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:48:08 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:48:22 IST" duration-ms="13525" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[microsoft]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[microsoft.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[usa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0987654321]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[12000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [microsoft]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [microsoft]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:48:22 IST" name="onTestFailure" finished-at="2025-06-16T18:48:22 IST" duration-ms="207" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=SKIP method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.reflect.Method)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:48:22 IST" name="initialization" finished-at="2025-06-16T18:50:19 IST" duration-ms="116177" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void TestCases.NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:50:19 IST" name="addNewCompany" data-provider="newCompaniesDetails" finished-at="2025-06-16T18:50:32 IST" duration-ms="13957" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[microsoft]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[microsoft.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[usa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0987654321]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[IT]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[12000]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [microsoft]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: company name is not matching expected [[LTI, infosys, tcs, wipro, capgemini, flipkart, amazon, alibaba, ebay, google, microsoft]] but found [microsoft]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at TestCases.NewCompany.addNewCompany(NewCompany.java:46)
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCompany -->
        <test-method is-config="true" signature="onTestFailure(org.testng.ITestResult)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:50:33 IST" name="onTestFailure" finished-at="2025-06-16T18:50:34 IST" duration-ms="1772" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCompany status=FAILURE method=NewCompany.addNewCompany(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.NewCompany@45099dd3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onTestFailure -->
        <test-method is-config="true" signature="onFinish(org.testng.ITestContext)[pri:0, instance:TestCases.NewCompany@45099dd3]" started-at="2025-06-16T18:50:34 IST" name="onFinish" finished-at="2025-06-16T18:50:35 IST" duration-ms="489" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@72e6e93]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onFinish -->
      </class> <!-- TestCases.NewCompany -->
    </test> <!-- NewCompanyTest -->
  </suite> <!-- Suite -->
</testng-results>
